## Ridge Regression L2

In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [81]:
df = pd.read_csv('/Users/zhichengliu/Desktop/Valar.Ga/Self_Learning.nosync/数据/Udemy/Python/UNZIP_FOR_NOTEBOOKS_FINAL/08-Linear-Regression-Models/Advertising.csv')

In [82]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [83]:
X = df.drop('sales', axis = 1)

In [84]:
y = df['sales']

In [85]:
from sklearn.preprocessing import PolynomialFeatures

In [86]:
polynomial_coverter = PolynomialFeatures(degree = 3, include_bias = False)

In [87]:
poly_features = polynomial_coverter.fit_transform(X)

In [88]:
poly_features.shape

(200, 19)

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [91]:
X_train.shape

(140, 19)

In [92]:
from sklearn.preprocessing import StandardScaler

In [93]:
scaler = StandardScaler()

In [94]:
scaler.fit(X_train)

StandardScaler()

In [95]:
X_train = scaler.transform(X_train)

In [96]:
X_test = scaler.transform(X_test)

In [97]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [98]:
poly_features[0] # 对比

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [99]:
from sklearn.linear_model import Ridge

In [100]:
ridge_model = Ridge(alpha = 10)

In [101]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [102]:
test_predictions = ridge_model.predict(X_test)

In [103]:
 from sklearn.metrics import mean_absolute_error,mean_squared_error

In [104]:
MAE = mean_absolute_error(y_test,test_predictions)

In [105]:
MAE

0.5774404204714181

In [106]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [107]:
RMSE

0.8946386461319672

In [108]:
from sklearn.linear_model import RidgeCV

In [109]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0))

In [110]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]))

In [111]:
ridge_cv_model.alpha_

0.1

In [112]:
#from sklearn.metrics import SCORERS

In [113]:
#SCORERS.keys()

In [114]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_percentage_error')

In [115]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]),
        scoring='neg_mean_absolute_percentage_error')

In [116]:
ridge_cv_model.alpha_

0.1

In [117]:
test_predictions = ridge_cv_model.predict(X_test)

In [118]:
MAE = mean_absolute_error(y_test, test_predictions)

In [119]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [120]:
MAE

0.4273774884329612

In [121]:
RMSE

0.618071992693697

In [122]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [123]:
ridge_cv_model.best_score_

-0.18908890318185512

## Lasso Regression L1

In [124]:
from sklearn.linear_model import LassoCV

In [125]:
lasso_cv_model = LassoCV(eps = 0.01,n_alphas=100, cv = 5) #max_iter= 1000000

In [126]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.01)

In [145]:
lasso_cv_model.alpha_

0.049430709092258295

In [128]:
test_predictions = lasso_cv_model.predict(X_test)

In [129]:
MAE = mean_absolute_error(y_test, test_predictions)

In [168]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [169]:
MAE

0.43350346185900707

In [170]:
RMSE

0.6063140748984027

In [133]:
lasso_cv_model.coef_

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

## Elastic net L1&L2

In [153]:
from sklearn.linear_model import ElasticNetCV

In [154]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas= 100, max_iter= 1000000)

In [155]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [156]:
elastic_model.l1_ratio_

1.0

In [157]:
elastic_model.alpha_

0.004943070909225827

In [163]:
test_predictions = elastic_model.predict(X_test)

In [164]:
MAE = mean_absolute_error(y_test, test_predictions)

In [165]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [166]:
MAE 

0.43350346185900707

In [167]:
RMSE

0.6063140748984027